title: CIS blog
author: College student
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The college student who tries to code and programming may start talking about his experiences in that blog.

# social links
github_username:  RostockerJung7 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
